apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: docker.io/ridhwan31/my-flask-app:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "100m"    # Limit CPU 512 millicpu (0.512 CPU)
              memory: "100Mi" # Limit memory 512 Mi (512MB)
