apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Ganti dengan nama image Docker kamu
        ports:
        - containerPort: 5000
