apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod  # Menunjukkan Issuer yang sudah dibuat
spec:
  rules:
  - host: "test.ridhwanerlangga.my.id"  # Ganti dengan domain kamu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              number: 80
  tls:
  - hosts:
    - "test.ridhwanerlangga.my.id"
    secretName: test-ridhwanerlangga-my-id-tls  # Sertifikat yang akan disimpan di secret
