apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000        # Port dalam service
      targetPort: 5000  # Port yang digunakan oleh aplikasi di kontainer
      nodePort: 30001   # Port yang dapat diakses dari luar cluster
  type: NodePort  # Ubah menjadi LoadBalancer jika kamu menggunakan cloud provider
