name: CI/CD Pipeline to K3s

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
    
    - name: Deploy to K3s using SSH
      uses: appleboy/ssh-action@v0.0.9
      with:
        host: ${{ secrets.K3S_HOST }}
        username: root
        key: ${{ secrets.K3S_SSH_KEY }}
        script: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl set image deployment/my-app my-app=${{ secrets.DOCKER_USERNAME }}/my-app:latest --namespace=default
          kubectl rollout status deployment/my-app --namespace=default

