name: CI/CD to Rancher

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ridhwan31/simple-web-app:latest

    - name: Trigger Rancher Redeploy
      run: |
        curl -k -X POST \
          https://82.112.236.166:444/v3/project/<project_id>/workloads/deployment:<namespace>:<workload_name>?action=redeploy \
          -H "Authorization: Bearer ${{ secrets.RANCHER_API_TOKEN }}"
